//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp_hopital_Ado.My_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class medecin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medecin()
        {
            this.soignes = new HashSet<soigne>();
        }
    
        public string id_medecin { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> dtn { get; set; }
        public string sexe { get; set; }
        public Nullable<int> id_specialitee_ { get; set; }
        public Nullable<int> id_service { get; set; }
    
        public virtual servicee servicee { get; set; }
        public virtual specialite specialite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soigne> soignes { get; set; }
    }
}
