//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tp_hopital_Ado.My_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HopitalEntities : DbContext
    {
        public HopitalEntities()
            : base("name=HopitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hopitale> hopitales { get; set; }
        public virtual DbSet<medecin> medecins { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<sejourne> sejournes { get; set; }
        public virtual DbSet<servicee> servicees { get; set; }
        public virtual DbSet<soigne> soignes { get; set; }
        public virtual DbSet<specialite> specialites { get; set; }
    }
}
